---
## Set system default settings
- name: "Update apt repository once"
  shell: "apt-get update && touch /tmp/.apt_get_updated_once"
  sudo: yes
  args:
    creates: "/tmp/.apt_get_updated_once"
  when: "{{ is_ubuntu | default(True) }} or {{ is_debian | default(False) }}"

- name: "Set hostname, if 'host_hostname' and 'host_fqdn' variables are defined"
  hostname: >
    name="{{ host_hostname }}"
  when: "('{{ host_hostname | default('X Y') }}' != 'X Y') and ('{{ host_fqdn | default('X Y') }}' != 'X Y')"

- name: "Set fqdn, if 'host_hostname' and 'host_fqdn' variables are defined"
  lineinfile: >
    line="127.0.0.1 {{ host_fqdn }} {{ host_hostname }}"
    state="present"
    dest="/etc/hosts"
  when: "('{{ host_hostname | default('X Y') }}' != 'X Y') and ('{{ host_fqdn | default('X Y') }}' != 'X Y')"

- name: "Set timezone as IST -- Ubuntu and debian"
  copy: >
    content="Asia/Kolkata"
    dest=/etc/timezone
    owner=root
    group=root
    mode=0644
  register: result
  when: "{{ is_ubuntu | default(True) }} or {{ is_debian | default(False) }}"

- name: "update timezone"
  command: dpkg-reconfigure --frontend noninteractive tzdata
  when: result|changed
  when: "{{ is_ubuntu | default(True) }} or {{ is_debian | default(False) }}"

- name: "Set timezone as IST -- CentOS"
  file: >
    src="/usr/share/zoneinfo/Asia/Kolkata"
    dest="/etc/localtime"
    force=yes
    state=link
  when: "{{ is_centos | default(False) }}"
